### ISSUE TITLE
Latest changes unreleased

### ISSUE THREAD

**Issue by tlvince** [socketio/socket.io-postgres-adapter#14]
The last release ([0.3.1](https://github.com/socketio/socket.io-postgres-adapter/releases/tag/0.3.1)) was 2023-02-08. Could a new release be published? I'm curious to see whether f783d4c568d232c40e47770e15763e97a77ed338 will help with an issue in my application.

Thanks for maintaining this package over the years!

**Comment by darrachequesne** [comment]
Here we go: https://github.com/socketio/socket.io-postgres-adapter/releases/tag/0.4.0
