### ISSUE TITLE
Will this adapter work with MS SQL Server ?

### ISSUE THREAD

**Issue by gsRatti1** [socketio/socket.io-postgres-adapter#9]
Hello, 

I need to use a socket io adapeter with MS SQL Server as persistent layer.
Can this adapter work for MS SQL Server or would I need to write my own adapter ?

What other options do I have for MS SQL Server ?

**Comment by darrachequesne** [comment]
No, unfortunately this adapter is not compatible with MS SQL Server.

We could create one official adapter though, if there is enough interest.
